### ISSUE TITLE
Mac users need Xcode for git

### ISSUE THREAD

**Issue by kbroman** [UW-Madison-ACI/boot-camps#114]
Need to update setup to have Mac users install Xcode.

**Comment by gidden** [comment]
I ran into this problem with a student on mac osx 10.6.8. We were able to
get things working with the git-osx-installer (
http://code.google.com/p/git-osx-installer/) _specifically_ the 1.7 series
(more specifically, 1.7.11 worked in this case).

tl;dr; mac osx 10.6.8 needs git-osx-installer 1.7.x

On Mon, Aug 25, 2014 at 9:39 AM, Karl Broman notifications@github.com
wrote:

> Need to update setup to have Mac users install Xcode.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/issues/114.

## 

Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by kbroman** [comment]
Another student using Mac OS X 10.8.5 also had problems. git ver 2 was getting a "symbol not found" for some /usr/lib system library.

Installing git 1.7.11, as @gidden suggested, also worked in this case.

**Comment by gidden** [comment]
closing this in favor of #117
