### ISSUE TITLE
Revert shell wildcard exercise to use /bin

### ISSUE THREAD

**Issue by gonuke** [UW-Madison-ACI/boot-camps#115]
The shell wildcard exercise was confusing because it required the `-d` flag to `ls` which is not intuitive.

This was changed to accommodate a lack of /bin on windows, but git bash does have /bin

**Comment by gidden** [comment]
We should also clarify for `-d` does.

On Mon, Aug 25, 2014 at 10:16 AM, Paul Wilson notifications@github.com
wrote:

> The shell wildcard exercise was confusing because it required the -d flag
> to ls which is not intuitive.
> 
> This was changed to accommodate a lack of /bin on windows, but git bash
> does have /bin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/issues/115.

## 

Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by lmichael107** [comment]
Both are fixed in 4d2597e and 527fb20
