### ISSUE TITLE
Update setup/installation instructions

### ISSUE THREAD

**Issue by gonuke** [UW-Madison-ACI/boot-camps#12]
Since we have chosen to try an approach that uses an ssh login to a single machine, we need setup/install instructions that reference that.

**Comment by gonuke** [comment]
Depends on #7.

**Comment by gonuke** [comment]
I just added a few lines as a "teaser" for installation instructions so that learners don't jump on the current installation instructions.  We might even want to take them out until we have this resolved.

**Comment by lmichael107** [comment]
I've added instructions OS-specific instructions, including links to Putty download/installation for Windows. I also moved "Alternate Installation Options" to another page. These two pages now link to eachother with descriptive text.

**Comment by lmichael107** [comment]
Also, you can get to the schedule and setup page from our main event page at http://software-carpentry.org/bootcamps/2013-04-wisc.html
