### ISSUE TITLE
setup: have participants test their installations first thing in the morning?

### ISSUE THREAD

**Issue by kbroman** [UW-Madison-ACI/boot-camps#122]
A number of participants had problems with git or with python/ipython that showed up later in the course; would have been nice to have discovered and corrected these problems during the setup time in the morning.

Maybe we should have students try out `git clone` and `ipython` and maybe `import nose` within python, after they've run the setup instructions.

(ipython wasn't working for one participant because he already had python installed and he'd not checked the "make anaconda the default python". Fixed by setting `PYTHONPATH="c/Anaconda"`.)

**Comment by gidden** [comment]
On Mon, Aug 25, 2014 at 1:54 PM, Karl Broman notifications@github.com
wrote:

> A number of participants had problems with git or with python/ipython that
> showed up laster in the course; would have been nice to have discovered and
> corrected these problems during the setup time in the morning.
> 
> Maybe we should have students try out git clone and ipython and maybe import
> nose within python, after they've run the setup instructions.
> 
> Most of the problems I have seen show up if you try some simple commands,
> e.g., `git -h`, `ipython -h`, `python -h`. Specifically for nose (and more
> complicated), I like `python -c "import nose; print nose.**version**".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/issues/122.

## 

Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by kbroman** [comment]
> Most of the problems I have seen show up if you try some simple commands, 
> e.g., `git -h`, `ipython -h`, `python -h`. Specifically for nose (and more 
> complicated), I like `python -c "import nose; print nose.**version**". 

Great; that's exactly what I had in mind.

**Comment by lmichael107** [comment]
Matt, do you want to add these to the top of the Setup page (or elsewhere) so that we can point participants to it? They're all just commands to run in the terminal (not within iPython, etc.), right?

**Comment by gidden** [comment]
I'll add them, and yes, these are all shell cmds.

On Mon, Jan 12, 2015 at 6:33 PM, lmichael107 notifications@github.com
wrote:

> Matt, do you want to add these to the top of the Setup page (or elsewhere)
> so that we can point participants to it? They're all just commands to run
> in the terminal (not within iPython, etc.), right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/issues/122#issuecomment-69668555
> .

## 

Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gonuke** [comment]
We learned this morning that it's "git --help" and that this was not sufficient for detecting someone with an incompatible OSX install of git.  This test passed but "git clone..." failed.

**Comment by gidden** [comment]
On Tue, Jan 13, 2015 at 2:02 PM, Paul Wilson notifications@github.com
wrote:

> We learned this morning that it's "git --help" and that this was not
> sufficient for detecting someone with an incompatible OSX install of git.
> This test passed but "git clone..." failed.
> 
> That's unfortunate... sorry for my tardiness on this issue. Would you still
> like me to update?

Also, it is likely `git --help` only on OSX and not other *nix distros;
`git -h` works at least on ubuntu.

> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/issues/122#issuecomment-69799126
> .

## 

Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by kliph** [comment]
This student needed to update to the latest version of git built for Snow Leopard (not Mavericks).  The student had OS X 10.8, which uses the older Snow Leopard build.

**Comment by gidden** [comment]
Would we still like to move on this issue, then? If so, how?

On Tue, Jan 13, 2015 at 2:20 PM, Cliff Rodgers notifications@github.com
wrote:

> This student needed to update to the latest version of git built for Snow
> Leopard (not Mavericks). The student had OS X 10.8, which uses the older
> Snow Leopard build.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/issues/122#issuecomment-69802363
> .

## 

Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by lmichael107** [comment]
I think the best bet would be to add the "Check Setup" commands to the
setup/Readme.md

Someone who's followed this conversation want to go for it? We could go
ahead and add it to this branch.

-Lauren

Lauren Michael - Research Computing Facilitator,
www.tinyurl.com/LMichaelCalendar, Discovery 2264, (608)316-4430
Center for High Throughput Computing http://chtc.cs.wisc.edu/; Advanced
Computing Initiative http://aci.wisc.edu/; Wisconsin Institute for
Discovery http://wid.wisc.edu/profile/lauren-michael/; ACI-REF
http://aci-ref.org/
University of Wisconsin - Madison
