### ISSUE TITLE
Two suggestions re pipes in automation session

### ISSUE THREAD

**Issue by kbroman** [UW-Madison-ACI/boot-camps#129]
In the automation session, in order to better motivate the use of pipes, we might precede the discussion of pipes with an example of the alternative: redirect output to a file, and then process that file with a second command.

Also, I'd skip the business about using `tail` with input from `stdin` (rather than a file). No one would really do that, and the whole `stdin` and `^-d` business seems confusing.

**Comment by lmichael107** [comment]
Addressed with e3dea39
