### ISSUE TITLE
Develop Pre-assessment questionnaire

### ISSUE THREAD

**Issue by gonuke** [UW-Madison-ACI/boot-camps#15]
Check with SWC for standard set of questions and tweak for our purposes

**Comment by gonuke** [comment]
In UW Google Drive - not linked here for privacy reasons

**Comment by gidden** [comment]
Hmm, do we need access (and if so, how do we get it? I'm not linked to the
uw google drive account that I know of).

Matthew Gidden
Nuclear Energy University Programs Fellow
The University of Wisconsin -- Madison
Ph. 225.892.3192
Fax 608.263.7451

**Comment by gonuke** [comment]
@lmichael107 will share the document and/or a summary of the responses
