### ISSUE TITLE
Add scipy to the learning envrionment

### ISSUE THREAD

**Issue by gidden** [UW-Madison-ACI/boot-camps#21]
When running through the testing examples, I got an error that scipy is not currently installed. Could we please get it installed @lmichael107 ? Thanks!

**Comment by lmichael107** [comment]
Sorry for the delay. This should happen sometime today.

Lauren

**Comment by gonuke** [comment]
Accomplished in EPD installation update

**Comment by lmichael107** [comment]
Hi All,

Thanks, again, for your involvement or interest in our April Software
Carpentry boot camp on the UW-Madison campus. We are now ~8 weeks from our
next planned boot camp and looking for instructors. I wanted to give all of
you first dibs on instructing or serving as an in-room helper. Please let
the group know if you would be interested. I've listed relevant materials
below.

Campus advertisement:
http://aci.wisc.edu/software-carpentry-bootcamp-august-29-30/
SWC boot camp page:
http://software-carpentry.org/bootcamps/2013-08-wisc.html
Curriculum from last boot camp (we intend to repeat):
http://uw-madison-aci.github.io/boot-camps/2013-04-29-uwmadison/index.html
GitHub repo of instruction materials:
https://github.com/UW-Madison-ACI/boot-camps

Thanks!

Lauren Michael
Research Computing Facilitator
Advanced Computing Infrastructure,
Center for High Throughput Computing, and
Wisconsin Institute for Discovery - Core Computational Technology

University of Wisconsin-Madison
330 N Orchard St
Madison, WI 53715
(608)316-4430
lmichael@wisc.edu
