### ISSUE TITLE
Add python flag to bash environment

### ISSUE THREAD

**Issue by gidden** [UW-Madison-ACI/boot-camps#22]
Currently, one gets the following error when running python in the environment:
/usr/local/lib/python2.6/site-packages/etsproxy-0.1.2-py2.6.egg/enthought/**init**.py:7: DeprecationWarning: enthought namespace imports are deprecated
  DeprecationWarning)

It's possible to fix this by appending a flag to the python call (-W ignore::DeprecationWarning), and we can make this universal  by adding the following to the bashrc_profile:

alias python='python -W ignore::DeprecationWarning'

However, this doesn't fix the issue for the testing environment, which runs nosetests, rather than straight python. I'd love to hear other's thoughts on the matter.

p.s., this is currently assigned to @lmichael107 because it deals with the environment; feel free to give it to someone else as needed

**Comment by gonuke** [comment]
@gidden - does the the EPD update fix this?

**Comment by gidden** [comment]
Yep, I no longer get the warning

Matthew Gidden
Nuclear Energy University Programs Fellow
The University of Wisconsin -- Madison
Ph. 225.892.3192
Fax 608.263.7451
