### ISSUE TITLE
Increase time for shell & automation

### ISSUE THREAD

**Issue by gonuke** [UW-Madison-ACI/boot-camps#50]
Despite our best efforts, we can't seem to cut the shell module down in time.  The current version (29e204c67f8f7fb4ef179d29e2ee60c77136f580) took 60 minutes to arrive at redirection and 75 minutes to complete.  This is 30 minutes more than allotted (66% too long).

We also never get to Make, something of great interest to users.

**Comment by lmichael107** [comment]
We did this, as we now have 1.5 hours, each, for the shell and automation portions. Though, we have foregone covering make in these topics.
