### ISSUE TITLE
Create list of gaps for learning environment

### ISSUE THREAD

**Issue by gonuke** [UW-Madison-ACI/boot-camps#6]
Each instructor should login to the machine and determine whether there are obstacles to teaching their curriculum that can be addressed by:
- common changes to the user shell environment
- additional software installation in shared user space
- additional software installation in needing root access/assistance

**Comment by gonuke** [comment]
Depends on #10

**Comment by lmichael107** [comment]
This has since been resolved, but we should keep a list of necessary software that needs to be installed.
