### ISSUE TITLE
Finalize curriculum topics

### ISSUE THREAD

**Issue by gonuke** [UW-Madison-ACI/boot-camps#9]
Review list of topics proposed by presenters and develop cohesive curriculum.

**Comment by gonuke** [comment]
@lmichael107, @gonuke, @katyhuff to meet on April 2.

**Comment by katyhuff** [comment]
sounds good to me...

**Comment by gonuke** [comment]
@lmichael107 @katyhuff @gonuke have drafted a curriculum around the Best Practice paper and will circulate for comment/feedback.
